name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
    - name: Export credentials
      run: export ${{ GITHUB_WORKSPACE.GOOGLE_APPLICATION_CREDENTIALS }}= /PLVisualizer/PLVisualizer.BusinessLogic/Clients/SpreadsheetsClient/credentials.json
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
    - name: Add submodules
      run: git submodule init && git submodule update
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build 
    - name: Test
      run: dotnet test
