name: .NET

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: projects/767680492690/locations/global/workloadIdentityPools/visualizer-pool/providers/visualizer-provider
        service_account: visualizer@snappy-mark-365811.iam.gserviceaccount.com
    - name: Export credentials
      run: export ${{ GOOGLE_APPLICATION_CREDENTIALS }}= /PLVisualizer/PLVisualizer.BusinessLogic/Clients/SpreadsheetsClient/credentials.json
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
    - name: Add submodules
      run: git submodule init && git submodule update
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build 
    - name: Test
      run: dotnet test
