name: .NET

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions: 
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3
      
      # Configure Workload Identity Federation via a credentials file.
    - id: 'auth'
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with: 
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
#      with:
#        workload_identity_provider: projects/767680492690/locations/global/workloadIdentityPools/visualizer-pool/providers/visualizer-provider
#        service_account: visualizer@snappy-mark-365811.iam.gserviceaccount.com
        
      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`. 
#    - name: 'Set up Cloud SDK'
#      uses: 'google-github-actions/setup-gcloud@v0'
#      
#      # Now you can run gcloud commands authenticated as the impersonated service account.
#    - id: 'gcloud'
#      name: 'gcloud'
#      run: |-
#        gcloud secrets versions access "latest" --secret "my-secret"
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
    - name: Add submodules
      run: git submodule init && git submodule update
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build 
    - name: Test
      run: dotnet test
